---
- name: windows update playbook
  hosts: all
  vars:
    ansible_connection=winrm
    ansible_winrm_transport=kerberos
    #ansible_user=your_ansible_user@YOUR.REALM.COM
    # Use a credential in AAP for the password, don't put it in inventory
    # ansible_password=YourPassword
    # Optional: if you use IP in ansible_host
    # ansible_winrm_kerberos_hostname_override=your_windows_host.your_domain.com
    ansible_winrm_server_cert_validation=ignore
  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true

